"""
AI Engineer YouTube Channel - Speaker Identification and LinkedIn Profile Finder
"""

import json
import re

# Speakers extracted from AI Engineer YouTube videos and conference pages
# Format: (Name, Company/Role, LinkedIn URL if found on conference page)

speakers_data = [
    # From YouTube Videos (visible in browser)
    {"name": "Jason Warner", "company": "Poolside", "linkedin": None, "video": "AGI: The Path Forward"},
    {"name": "Eiso Kant", "company": "Poolside", "linkedin": None, "video": "AGI: The Path Forward"},
    {"name": "Aman Khan", "company": "Arize", "linkedin": None, "video": "Shipping AI That Works: An Evaluation Framework for PMs"},
    {"name": "Jared Zoneraich", "company": "PromptLayer", "linkedin": None, "video": "How Claude Code Works"},
    {"name": "Joel Becker", "company": "METR", "linkedin": None, "video": "Why METR is measuring Agent and Human productivity"},
    {"name": "Asaf Bord", "company": "Northwestern Mutual", "linkedin": None, "video": "Small Bets, Big Impact Building GenBI at a Fortune 100"},
    {"name": "Max Kanat-Alexander", "company": "Capital One", "linkedin": None, "video": "Developer Experience in the Age of AI Coding Agents"},
    {"name": "Aparna Dhinakaran", "company": "Arize", "linkedin": "https://twitter.com/aparnadhinak", "video": "The Unreasonable Effectiveness of Prompt Learning"},
    {"name": "Beyang Liu", "company": "Sourcegraph", "linkedin": "https://www.linkedin.com/in/beyang-liu/", "video": "Amp Code: Next Generation AI Coding"},
    {"name": "Eno Reyes", "company": "Factory AI", "linkedin": "https://www.linkedin.com/in/enoreyes/", "video": "Making Codebases Agent Ready"},
    {"name": "Michele Catasta", "company": "Replit", "linkedin": None, "video": "The 3 Pillars of Autonomy"},
    {"name": "swyx", "company": "Latent.Space", "linkedin": "https://twitter.com/swyx", "video": "The War on Slop"},
    {"name": "Jake Nations", "company": "Netflix", "linkedin": None, "video": "The Infinite Software Crisis"},
    {"name": "Samir Mody", "company": "The Browser Company of New York", "linkedin": None, "video": "From Arc to Dia: Lessons learned building AI Browsers"},
    {"name": "Justin Reock", "company": "DX (acq. Atlassian)", "linkedin": None, "video": "Leadership in AI Assisted Engineering"},
    {"name": "Arman Hezarkhani", "company": "Tenex", "linkedin": None, "video": "Paying Engineers like Salespeople"},
    {"name": "Alex Lieberman", "company": "Tenex", "linkedin": None, "video": "AI Leadership"},
    {"name": "Dan Shipper", "company": "Every, AI & I", "linkedin": None, "video": "Dispatch from the Future: building an AI-native Company"},
    {"name": "NLW", "company": "Super ai", "linkedin": None, "video": "AI Consulting in Practice"},
    {"name": "Jacob Kahn", "company": "FAIR Meta", "linkedin": None, "video": "Code World Model: Building World Models for Computation"},
    {"name": "Natalie Serrino", "company": "Gimlet Labs", "linkedin": None, "video": "AI Kernel Generation"},
    {"name": "Lisa Orr", "company": "Zapier", "linkedin": None, "video": "Your Support Team Should Ship Code"},
    {"name": "Lei Zhang", "company": "Bloomberg", "linkedin": None, "video": "What We Learned Deploying AI within Bloomberg's Engineering Organization"},
    {"name": "Kat Kampf", "company": "Google DeepMind", "linkedin": None, "video": "Building in the Gemini Era"},
    {"name": "Ammaar Reshi", "company": "Google DeepMind", "linkedin": None, "video": "Building in the Gemini Era"},
    {"name": "Naman Jain", "company": "Cursor", "linkedin": None, "video": "Coding Evals: From Code Snippets to Codebases"},
    {"name": "Kitze", "company": "Sizzy", "linkedin": None, "video": "From Vibe Coding To Vibe Engineering"},
    {"name": "Olive Song", "company": "MiniMax", "linkedin": None, "video": "Minimax M2: Building the #1 Open Model"},
    {"name": "Kath Korevec", "company": "Google Labs", "linkedin": None, "video": "Proactive Agents"},
    {"name": "Martin Harrysson", "company": "McKinsey & Company", "linkedin": None, "video": "Moving away from Agile: What's Next"},
    {"name": "Natasha Maniar", "company": "McKinsey & Company", "linkedin": None, "video": "Moving away from Agile: What's Next"},
    {"name": "Nik Pash", "company": "Cline", "linkedin": None, "video": "Hard Won Lessons from Building Effective AI Coding Agents"},
    {"name": "Itamar Friedman", "company": "Qodo", "linkedin": None, "video": "The State of AI Code Quality: Hype vs Reality"},
    
    # From AI Engineer World's Fair 2024 Conference Page
    {"name": "Chris Lattner", "company": "Modular CEO", "linkedin": "https://www.linkedin.com/in/chris-lattner-5664498a/", "video": None},
    {"name": "Justine Tunney", "company": "Mozilla, Llamafile", "linkedin": "https://twitter.com/JustineTunney", "video": None},
    {"name": "Thomas Dohmke", "company": "GitHub CEO", "linkedin": "https://twitter.com/ashtom", "video": None},
    {"name": "Lin Qiao", "company": "Fireworks CEO", "linkedin": "https://www.linkedin.com/in/lin-qiao-22248b4/", "video": None},
    {"name": "Alex Albert", "company": "Anthropic, Head of Developer Relations", "linkedin": "https://twitter.com/alexalbert__", "video": None},
    {"name": "Romain Huet", "company": "OpenAI, Head of Developer Experience", "linkedin": "https://twitter.com/romainhuet/", "video": None},
    {"name": "Simon Willison", "company": "Independent, Legendary AI Engineer", "linkedin": "https://twitter.com/simonw/", "video": None},
    {"name": "Scott Wu", "company": "Cognition (Devin) CEO", "linkedin": "https://www.linkedin.com/in/scott-wu-8b94ab96/", "video": None},
    {"name": "Stefania Druga", "company": "Google, Research Scientist Gemini", "linkedin": "https://twitter.com/Stefania_druga", "video": None},
    {"name": "Daniel Han", "company": "Unsloth CEO", "linkedin": "https://www.linkedin.com/in/danielhanchen/", "video": None},
    {"name": "Devendra Chaplot", "company": "Mistral, Research Scientist", "linkedin": "https://www.linkedin.com/in/devendra-chaplot-b1605534/", "video": None},
    {"name": "Dylan Patel", "company": "SemiAnalysis, Chief Analyst", "linkedin": "https://twitter.com/dylan522p", "video": None},
    {"name": "Keelin McDonell", "company": "Google, Product Manager Vertex AI", "linkedin": "https://twitter.com/keelinmc", "video": None},
    {"name": "Sandra Kublik", "company": "Cohere, Developer Advocate", "linkedin": "https://twitter.com/itsSandraKublik", "video": None},
    {"name": "Vivek Muppalla", "company": "Cohere, Director Of Engineering", "linkedin": "https://www.linkedin.com/in/vivekmuppalla/", "video": None},
    {"name": "Lukas Biewald", "company": "Weights & Biases CEO", "linkedin": "https://www.linkedin.com/in/lbiewald", "video": None},
    {"name": "Cheng Lou", "company": "Midjourney, Member of Technical Staff", "linkedin": "https://www.linkedin.com/in/cheng-lou-8270a2176/", "video": None},
    {"name": "Shelby Heinecke", "company": "Salesforce, Senior AI Research Manager", "linkedin": "https://twitter.com/shelbyh_ai", "video": None},
    {"name": "Harrison Chase", "company": "LangChain CEO", "linkedin": "https://www.linkedin.com/in/harrison-chase-961287118/", "video": None},
    {"name": "Jerry Liu", "company": "LlamaIndex CEO", "linkedin": "https://www.linkedin.com/in/jerry-liu-64390071/", "video": None},
    {"name": "Ben Hylak", "company": "Dawn Analytics CPO", "linkedin": "https://www.linkedin.com/in/benhylak/", "video": None},
    {"name": "Kathleen Kenealy", "company": "DeepMind, Staff Research Engineer", "linkedin": "https://www.linkedin.com/in/kathleen-kenealy/", "video": None},
    {"name": "Noah Shpak", "company": "Character.ai, Member of Technical Staff", "linkedin": "https://www.linkedin.com/in/nshpak/", "video": None},
    {"name": "Karan Goel", "company": "Cartesia CEO", "linkedin": "https://twitter.com/krandiash", "video": None},
    {"name": "Michael Truell", "company": "Cursor CEO", "linkedin": "https://mntruell.com/", "video": None},
    {"name": "Antje Barth", "company": "AWS, Principal Developer Advocate", "linkedin": "https://www.linkedin.com/in/antje-barth/", "video": None},
    {"name": "Ahmed Menshawy", "company": "Mastercard, Vice President of AI Engineering", "linkedin": "https://linkedin.com/in/ahmed-menshawy", "video": None},
    {"name": "Heejin Jeong", "company": "Together, Principal AI PM", "linkedin": "https://www.linkedin.com/in/heejin-chloe-jeong/", "video": None},
    {"name": "Shreya Shankar", "company": "UC Berkeley EECS & EPIC Lab", "linkedin": "https://twitter.com/sh_reya", "video": None},
    {"name": "Zack Witten", "company": "Anthropic, Staff Prompt Engineer", "linkedin": "https://twitter.com/zswitten", "video": None},
    {"name": "Jason Liu", "company": "Independent, Consultant (Instructor)", "linkedin": "https://twitter.com/jxnlco", "video": None},
    {"name": "Ian Webster", "company": "Discord, Senior Staff Software Engineer", "linkedin": "https://linkedin.com/in/ianww", "video": None},
    {"name": "Sunny Madra", "company": "Groq, GM of GroqCloud", "linkedin": "https://www.linkedin.com/in/sundeepm/", "video": None},
    {"name": "Mark Moyou", "company": "NVIDIA, Sr. Data Scientist", "linkedin": "https://twitter.com/MarkMoyou", "video": None},
    {"name": "Nikhil Thota", "company": "Perplexity, Member of Technical Staff", "linkedin": "https://linkedin.com/in/thot", "video": None},
    {"name": "Shawn Jansepar", "company": "Khan Academy, Director of Engineering", "linkedin": "https://linkedin.com/in/jansepar", "video": None},
    {"name": "Ankur Goyal", "company": "Braintrust CEO", "linkedin": "https://twitter.com/ankrgyl", "video": None},
    {"name": "Phoebe Klett", "company": "Normal Computing, ML Engineer", "linkedin": "https://twitter.com/KlettPhoebe", "video": None},
    {"name": "Emil Eifrem", "company": "Neo4j CEO", "linkedin": "https://twitter.com/emileifrem", "video": None},
    {"name": "Atita Arora", "company": "Qdrant, Solution Architect", "linkedin": "https://twitter.com/atitaarora", "video": None},
    {"name": "Kwindla Hultman Kramer", "company": "Daily CEO", "linkedin": "https://twitter.com/kwindla", "video": None},
    {"name": "Bryan Bischof", "company": "Hex, Head of AI", "linkedin": "https://twitter.com/BEBischof", "video": None},
    {"name": "Stephen Hood", "company": "Mozilla, Open Source AI Lead", "linkedin": "https://twitter.com/stlhood", "video": None},
    {"name": "Scott Stephenson", "company": "Deepgram CEO", "linkedin": "https://twitter.com/deepgramscott", "video": None},
    {"name": "Daniel Whitenack", "company": "Prediction Guard CEO", "linkedin": "https://twitter.com/dwhitena", "video": None},
    {"name": "Thierry Moreau", "company": "OctoAI, Co-Founder", "linkedin": None, "video": None},
    {"name": "Dominik Kundel", "company": "Twilio, Head of Product & Design", "linkedin": "https://www.linkedin.com/in/dkundel/", "video": None},
    {"name": "Shyamal Anadkat", "company": "OpenAI, Startup Solutions Lead", "linkedin": "https://www.linkedin.com/in/zostale/", "video": None},
    {"name": "Toki Sherbakov", "company": "OpenAI, Head of Solutions Architecture", "linkedin": "https://twitter.com/tokisherbakov", "video": None},
    {"name": "Arjun Bansal", "company": "Log10 CEO", "linkedin": "https://linkedin.com/in/arjunbansal", "video": None},
    {"name": "Eugene Yan", "company": "Amazon, Senior Applied Scientist", "linkedin": "https://eugeneyan.com/", "video": None},
    {"name": "Jamie Turner", "company": "Convex CEO", "linkedin": "https://twitter.com/jamwt", "video": None},
    {"name": "Fryderyk Wiatrowski", "company": "Zeta Labs, Co-founder", "linkedin": "https://twitter.com/fawiatrowski", "video": None},
    {"name": "Greg Baugues", "company": "HaiHai Labs, Founder", "linkedin": "https://www.linkedin.com/in/gregbaugues/", "video": None},
    {"name": "Gunjan Patel", "company": "Palo Alto Networks, Director of Engineering", "linkedin": "https://www.linkedin.com/in/gunjanpatel1/", "video": None},
    {"name": "Hamel Husain", "company": "Parlance Labs, Founder", "linkedin": "https://www.linkedin.com/in/hamelhusain/", "video": None},
    {"name": "Hubert Misztela", "company": "Novartis, AI Researcher/Director of Data Science", "linkedin": "https://twitter.com/hubert_misztela", "video": None},
    {"name": "Ishan Anand", "company": "Independent, Spreadsheets Are All You Need", "linkedin": "https://linkedin.com/in/ishananand", "video": None},
    {"name": "Rahul Pandita", "company": "GitHub, Automated Software Engineering Researcher", "linkedin": "https://www.linkedin.com/in/panditarahul", "video": None},
    {"name": "Jeronim Morina", "company": "AXA, Senior MLOps Engineer", "linkedin": "https://linkedin.com/in/jeronim-morina", "video": None},
    {"name": "Deanna Emery", "company": "Quotient, Founding AI Researcher", "linkedin": "https://www.linkedin.com/in/deanna-emery/", "video": None},
    {"name": "João Moura", "company": "crewAI CEO", "linkedin": "https://www.linkedin.com/in/joaomdmoura/", "video": None},
    {"name": "Kyle Corbitt", "company": "OpenPipe, Founder & CEO", "linkedin": "https://twitter.com/corbtt", "video": None},
    {"name": "Karan Singh", "company": "AWS, Generative AI PM", "linkedin": "https://www.linkedin.com/in/karan-singh-a8aa7518/", "video": None},
    {"name": "Kevin Van Gundy", "company": "Hypermode CEO", "linkedin": "https://linkedin.com/in/kevinvangundy", "video": None},
    {"name": "Maxime Labonne", "company": "Liquid AI, Senior Staff ML Scientist", "linkedin": "https://twitter.com/maximelabonne", "video": None},
    {"name": "Morgante Pell", "company": "Grit CEO", "linkedin": "https://twitter.com/morgantepell", "video": None},
    {"name": "Pankaj Gupta", "company": "Baseten, Co-Founder", "linkedin": "https://twitter.com/defpan", "video": None},
    {"name": "Patrick Debois", "company": "Independent, Ex. VP ENG Showpad", "linkedin": "https://twitter.com/patrickdebois", "video": None},
    {"name": "Paul Henry", "company": "BotDojo CEO", "linkedin": "https://www.linkedin.com/in/pauldhenry/", "video": None},
    {"name": "Philip Kiely", "company": "Baseten, Head of Developer Relations", "linkedin": "https://twitter.com/philip_kiely", "video": None},
    {"name": "Phlo Young", "company": "Independent, Rapper", "linkedin": "https://twitter.com/YoungPhlo_", "video": None},
    {"name": "Benjamin Stein", "company": "Perpetual CEO", "linkedin": "https://linkedin.com/in/benjaminstein", "video": None},
    {"name": "Charles Frye", "company": "Modal Labs, AI Engineer", "linkedin": "https://twitter.com/charles_irl", "video": None},
    {"name": "Ryan Fox-Tyler", "company": "Hypermode, SVP of Products and Engineering", "linkedin": "https://www.linkedin.com/in/ryanfoxtyler/", "video": None},
    {"name": "Rémi Louf", "company": ".txt (Outlines) CEO", "linkedin": "https://twitter.com/remilouf", "video": None},
    {"name": "Emil Sedgh", "company": "Rechat CTO", "linkedin": "https://twitter.com/emilsedgh", "video": None},
    {"name": "Sumit Agarwal", "company": "Ario CEO", "linkedin": "https://www.linkedin.com/in/sumitagarwalusaf/", "video": None},
    {"name": "Damien Murphy", "company": "Deepgram, Senior Applied Engineer", "linkedin": "https://www.linkedin.com/in/damienm1/", "video": None},
    {"name": "Tanmai Gopal", "company": "Hasura CEO", "linkedin": "https://twitter.com/tanmaigo", "video": None},
    {"name": "Tom Redman", "company": "Convex, Head of DX", "linkedin": "https://twitter.com/redman", "video": None},
    {"name": "Sheila Gulati", "company": "Tola Capital, Managing Director", "linkedin": "https://www.linkedin.com/in/sheilagulati/", "video": None},
    {"name": "Vasek Mlejnsky", "company": "E2B CEO", "linkedin": "https://twitter.com/mlejva", "video": None},
    {"name": "Vibhor Kumar", "company": "Tinder, AI Engineer", "linkedin": "https://linkedin.com/in/kumarvibhor", "video": None},
    {"name": "Sualeh Asif", "company": "Cursor, AI Engineer", "linkedin": "https://www.sualehasif.me/", "video": None},
    {"name": "Derek Bingham", "company": "AWS, Senior Developer Advocate", "linkedin": "https://www.linkedin.com/in/derekwbingham/", "video": None},
    {"name": "Kevin Hou", "company": "Windsurf, Head of Product Engineering", "linkedin": "https://twitter.com/kevinhou22", "video": None},
    {"name": "Peter Cooper", "company": "CooperPress, GitHub user #118", "linkedin": "https://twitter.com/cooperx86", "video": None},
    {"name": "Nischal Nadhamuni", "company": "Klarity CTO", "linkedin": "https://twitter.com/_nischaln", "video": None},
    {"name": "Manuel Odendahl", "company": "The Tree Center, Principal Engineer", "linkedin": "https://linkedin.com/in/manuel-odendahl-a2369122", "video": None},
    {"name": "Vikhyat Korrapati", "company": "M87 Labs CTO", "linkedin": "https://twitter.com/vikhyatk", "video": None},
    {"name": "Santosh Radha", "company": "Agnostiq (Covalent), Head of Product/Research", "linkedin": "https://www.linkedin.com/in/santoshkumarradha/", "video": None},
    {"name": "Olmo Maldonado", "company": "Zapier, Sr. AI Engineer", "linkedin": "https://twitter.com/ibolmo", "video": None},
    {"name": "Alex Volkov", "company": "Weights & Biases, AI Evangelist", "linkedin": "https://twitter.com/altryne", "video": None},
    {"name": "Prakul Agarwal", "company": "MongoDB, Sr. Product Manager ML", "linkedin": "https://www.linkedin.com/in/prakulagarwal/", "video": None},
    {"name": "Azul Garza", "company": "Nixtla, CTO & Co-Founder", "linkedin": "https://www.linkedin.com/in/azul-garza-ramirez/", "video": None},
    {"name": "Apoorva Joshi", "company": "MongoDB, Sr. AI Developer Advocate", "linkedin": "https://www.linkedin.com/in/apoorvajoshi95/", "video": None},
    {"name": "Henry Weller", "company": "MongoDB, Product Manager", "linkedin": "https://www.linkedin.com/in/henryweller/", "video": None},
    {"name": "Ben Perlmutter", "company": "MongoDB, Sr. Engineer Chatbot Framework", "linkedin": "https://www.linkedin.com/in/ben-perlmutter/", "video": None},
    {"name": "Pedro Torruella", "company": "OctoAI, Staff DevRel Engineer", "linkedin": "https://www.linkedin.com/in/ptorru/", "video": None},
    {"name": "Ivan Leo", "company": "567 Labs (Instructor), Research Engineer", "linkedin": "https://twitter.com/ivanleomk", "video": None},
    {"name": "Leo Pekelis", "company": "Gradient, Chief Scientist", "linkedin": "https://linkedin.com/in/leonid-pekelis", "video": None},
    {"name": "Fabian Valle", "company": "MongoDB, Sr. Engineer", "linkedin": "https://www.linkedin.com/in/fabian-valle-24b22b149/", "video": None},
    {"name": "Lance Martin", "company": "LangChain, AI Engineer", "linkedin": "https://www.linkedin.com/in/lance-martin-64a33b5/", "video": None},
    {"name": "Nicolai Baldin", "company": "Synthesized.io CEO", "linkedin": "https://www.linkedin.com/in/nbaldin/", "video": None},
    {"name": "Trey Doig", "company": "Echo AI CTO", "linkedin": "https://www.linkedin.com/in/treydoig/", "video": None},
    {"name": "Chang She", "company": "LanceDB CEO", "linkedin": "https://www.linkedin.com/in/changshe/", "video": None},
    {"name": "Ben Flast", "company": "MongoDB, Director of Product", "linkedin": "https://www.linkedin.com/in/benjamin-flast/", "video": None},
    {"name": "Peter Albert", "company": "Zeta Labs, Co-Founder", "linkedin": "https://www.linkedin.com/in/peter-k-albert/", "video": None},
    {"name": "Quinn Slack", "company": "Sourcegraph CEO", "linkedin": "https://www.linkedin.com/in/quinnslack/", "video": None},
    {"name": "Philip Rathle", "company": "Neo4j CTO", "linkedin": "https://www.linkedin.com/in/prathle/", "video": None},
    {"name": "Raza Habib", "company": "Humanloop, CEO and Co-Founder", "linkedin": "https://www.linkedin.com/in/humanloop-raza/", "video": None},
    {"name": "Aurimas Griciūnas", "company": "Neptune CPO", "linkedin": "https://twitter.com/Aurimas_Gr", "video": None},
    {"name": "YK Sugi", "company": "Sourcegraph, AI Developer Advocate", "linkedin": "https://twitter.com/ykdojo", "video": None},
    {"name": "Phil Nash", "company": "Datastax, Developer Relations Engineer", "linkedin": "https://philna.sh/", "video": None},
    {"name": "Benjamin Fletcher", "company": "EyeLevel.ai CEO", "linkedin": "https://www.linkedin.com/in/benjamin-fletcher-bb73334/", "video": None},
    {"name": "Alex Malebranche", "company": "GitHub, Global Engagement Lead", "linkedin": "https://www.linkedin.com/in/boytwigg/", "video": None},
    {"name": "Dave Burnison", "company": "GitHub, Senior Developer Advocate", "linkedin": "https://www.linkedin.com/in/daveburnison/", "video": None},
    {"name": "Chris Rec", "company": "WhyHow.AI, Co-Founder", "linkedin": "https://www.linkedin.com/in/chrisrec/", "video": None},
    {"name": "Karthik Suresh", "company": "Ignition CPTO", "linkedin": "https://www.linkedin.com/in/karthiksureshlbs/", "video": None},
    {"name": "Gabriel Paunescu", "company": "Naologic CEO", "linkedin": "https://www.linkedin.com/in/gabrielpaunescu/", "video": None},
    {"name": "Gabriela de Queiroz", "company": "Microsoft, Director of AI for Startups", "linkedin": "https://www.linkedin.com/in/gabrieladequeiroz/", "video": None},
    {"name": "Aishwarya Srinivasan", "company": "Microsoft, Senior AI Advisor", "linkedin": "https://linkedin.com/in/aishwarya-srinivasan", "video": None},
    {"name": "Cedric Vidal", "company": "Microsoft, Principal AI Advocate", "linkedin": "https://www.linkedin.com/in/cedricvidal/", "video": None},
    {"name": "David Smith", "company": "Microsoft, Principal Cloud Advocate", "linkedin": "https://www.linkedin.com/in/dmsmith/", "video": None},
    {"name": "Banjo Obayomi", "company": "AWS, Senior Developer Advocate", "linkedin": "https://twitter.com/banjtheman", "video": None},
    {"name": "Sarah Buchner", "company": "Trunk Tools CEO", "linkedin": "https://www.linkedin.com/in/sarah-buchner", "video": None},
    {"name": "Rob Cheung", "company": "Substrate CEO", "linkedin": "https://twitter.com/perceptnet", "video": None},
    {"name": "Andreas Kolleger", "company": "Neo4j, Knowledge Engineer", "linkedin": "https://www.linkedin.com/in/akollegger/", "video": None},
    {"name": "Kibeom Lee", "company": "Sendbird, Lead Machine Learning Engineer", "linkedin": "https://www.linkedin.com/in/kibeomlee/", "video": None},
    {"name": "Dimitrios Philliou", "company": "GitHub, Product Manager", "linkedin": "https://www.linkedin.com/in/dimitriosphilliou/", "video": None},
    {"name": "Satya Nitta", "company": "Emergence, Co-founder and CEO", "linkedin": "https://www.linkedin.com/in/satya-nitta-5554984/", "video": None},
    {"name": "Christina Warren", "company": "GitHub, Senior Developer Advocate", "linkedin": "https://www.linkedin.com/in/filmgirl/", "video": None},
    {"name": "Christopher Harrison", "company": "GitHub, Senior Developer Advocate", "linkedin": "https://www.linkedin.com/in/geektrainer/", "video": None},
    {"name": "Pablo Castro", "company": "Microsoft, Distinguished Engineer", "linkedin": "https://www.linkedin.com/in/pabloc/", "video": None},
    {"name": "Pamela Fox", "company": "Microsoft, Principal Cloud Advocate (Python)", "linkedin": "https://twitter.com/pamelafox", "video": None},
    {"name": "Harald Kirschner", "company": "Microsoft, Principal Product Manager", "linkedin": "https://www.linkedin.com/in/digitarald/", "video": None},
    {"name": "Lachlan Ainley", "company": "Microsoft, Senior PMM", "linkedin": "https://www.linkedin.com/in/lachlanainley/", "video": None},
    {"name": "Ray Thai", "company": "Fireworks, Founding Product Manager", "linkedin": "https://www.linkedin.com/in/raymondcthai/", "video": None},
    {"name": "Sarah Khalife", "company": "GitHub, Principal Solutions Engineer", "linkedin": "https://www.linkedin.com/in/sarahkhalife/", "video": None},
    {"name": "Yasir Al-Ibrahem", "company": "GitHub, Principal Solutions Engineer", "linkedin": "https://github.com/YasirAlibrahem", "video": None},
    {"name": "Nathan Peck", "company": "AWS, Senior Developer Advocate", "linkedin": "https://twitter.com/nathankpeck", "video": None},
    {"name": "Darko Mesaros", "company": "AWS, Principal Developer Advocate", "linkedin": "https://twitter.com/darkosubotica", "video": None},
    {"name": "Vinicius Senger", "company": "AWS, Senior Developer Advocate", "linkedin": "https://twitter.com/siliconvini", "video": None},
    {"name": "Holt Skinner", "company": "Google, Developer Advocate", "linkedin": "https://twitter.com/HoltSkinner12", "video": None},
    {"name": "Rick Lamers", "company": "Groq, AI Researcher/Engineer", "linkedin": "https://twitter.com/RickLamers", "video": None},
    {"name": "Paul Sebexen", "company": "Lambda Labs, Cloud Engineering", "linkedin": "https://www.linkedin.com/in/paul-sebexen-59204625", "video": None},
    {"name": "Tirumarai Selvan", "company": "Hasura, Principal Product Manager", "linkedin": "https://www.linkedin.com/in/tirumarai-selvan-384a8517/", "video": None},
    {"name": "Yash Sheth", "company": "Galileo, Co-founder & COO", "linkedin": "https://twitter.com/YashSheth46", "video": None},
    {"name": "Aaron Dignan", "company": "Plumb, Co-Founder", "linkedin": "https://www.linkedin.com/in/aarondignan/", "video": None},
    {"name": "Shreyas Sreenivas", "company": "Exa, Founding Engineer", "linkedin": "https://twitter.com/shreyas4_", "video": None},
    {"name": "Justin McCarty", "company": "Ionic Commerce, CEO & Co-Founder", "linkedin": "https://twitter.com/JustinDMcCarty", "video": None},
    {"name": "Taranveer Singh", "company": "Chegg, AI/ML Lead", "linkedin": "https://www.linkedin.com/in/taranveer/", "video": None},
    {"name": "Ievgen Vakulenko", "company": "Crusoe, Product Manager", "linkedin": "https://www.linkedin.com/in/evakulen/", "video": None},
    {"name": "Jamie Neuwirth", "company": "Anthropic, Head of Startup Sales", "linkedin": "https://twitter.com/jneuwirth4", "video": None},
    {"name": "Nicolas Schlaepfer", "company": "Hyperspace, VP AI R&D", "linkedin": "https://www.linkedin.com/in/nicolas-s-138564187/", "video": None},
    {"name": "Tamer Abuelsaad", "company": "Emergence, Principal Engineer", "linkedin": "https://github.com/EmergenceAI/Agent-E", "video": None},
    {"name": "Andrew Davis", "company": "HiddenLayer, Chief Data Scientist", "linkedin": "https://www.linkedin.com/in/andrew-davis-08985990/", "video": None},
    {"name": "Alison Cossette", "company": "Neo4j, Data Science Strategist", "linkedin": "https://twitter.com/alison_cossette", "video": None},
    
    # From AI Engineer Summit 2025
    {"name": "Grace Isford", "company": "Lux Capital", "linkedin": None, "video": "Beyond the Consensus: Navigating AI's Frontier in 2025"},
    {"name": "Greg Ceccarelli", "company": "SpecStory", "linkedin": None, "video": "How To Build an AI Strategy That Fails"},
    {"name": "Don Bosco Durai", "company": "Privacera", "linkedin": None, "video": "Balancing Innovation with Security & Safety"},
    {"name": "Colin Flaherty", "company": "Augment Code", "linkedin": None, "video": "Building Self-Coding Agents"},
    {"name": "Baptiste Rozière", "company": "Mistral", "linkedin": None, "video": "Mistral for VPs of AI"},
    {"name": "Leigh Pember", "company": "Mistral", "linkedin": None, "video": "Mistral for VPs of AI"},
    {"name": "Stephen Chin", "company": "Neo4j", "linkedin": None, "video": "Anchoring Enterprise GenAI with Knowledge Graphs"},
    {"name": "Jonathan Lowe", "company": "Pfizer", "linkedin": None, "video": "Anchoring Enterprise GenAI with Knowledge Graphs"},
    {"name": "Bruno Passos", "company": "Booking.com", "linkedin": None, "video": "Building AI Agents with Real ROI in the Enterprise SDLC"},
    {"name": "Waseem Alshikh", "company": "Writer CTO", "linkedin": None, "video": "Building Trust in Enterprise AI"},
    {"name": "Prashant Mital", "company": "OpenAI", "linkedin": None, "video": "OpenAI for VPs of AI"},
    {"name": "Barr Yaron", "company": "Amplify Partners", "linkedin": None, "video": "Frontier Feud"},
    {"name": "Shirsha Chaudhuri", "company": "Thomson Reuters", "linkedin": None, "video": "Missing pieces of workflow automation"},
    {"name": "Diamond Bishop", "company": "Datadog", "linkedin": None, "video": "The Devops Engineer Who Never Sleeps"},
    {"name": "Paul Gilbert", "company": "Arista Networks", "linkedin": None, "video": "How to Build Your Own AI Data Center in 2025"},
    {"name": "Alexander Bricken", "company": "Anthropic", "linkedin": None, "video": "Anthropic for VPs of AI"},
    {"name": "Joe Bayley", "company": "Anthropic", "linkedin": None, "video": "Anthropic for VPs of AI"},
    {"name": "Heath Black", "company": "SignalFire", "linkedin": None, "video": "Insights on Building AI teams"},
    {"name": "Xiaofeng Wang", "company": "LinkedIn", "linkedin": None, "video": "Lessons from Building LinkedIn's GenAI Platform"},
    {"name": "Douwe Kiela", "company": "Contextual AI", "linkedin": None, "video": "Specialized RAG Agents"},
    {"name": "Sayash Kapoor", "company": "AI Snake Oil", "linkedin": None, "video": "Building and evaluating AI Agents That Matter"},
    {"name": "Mukund Sridhar", "company": "DeepMind", "linkedin": None, "video": "Going deep on Gemini Deep Research"},
    {"name": "Aarush Selvan", "company": "Google Gemini", "linkedin": None, "video": "Going deep on Gemini Deep Research"},
    {"name": "Barry Zhang", "company": "Anthropic", "linkedin": None, "video": "How We Build Effective Agents"},
    {"name": "Zack Reneau-Wedeen", "company": "Sierra", "linkedin": None, "video": "Sierra's Agent Development Life Cycle"},
    {"name": "Will Brown", "company": "Morgan Stanley", "linkedin": None, "video": "What RL Means for Agents"},
    {"name": "Brennan Rosales", "company": "BlackRock", "linkedin": None, "video": "Agents in Investment Management: Aladdin Copilot"},
    {"name": "John Crepezzi", "company": "Jane Street", "linkedin": None, "video": "Building AI-Powered Developer Tools at Jane Street"},
    {"name": "Anju Kambadur", "company": "Bloomberg", "linkedin": None, "video": "Challenges to Scaling Agents for Generative AI Products"},
    {"name": "Mike Conover", "company": "Brightwave", "linkedin": None, "video": "Trust, but Verify: High-Fidelity Reasoning in Agentic Workflows"},
    {"name": "Evan Fossier", "company": "Datadog", "linkedin": None, "video": "How do you know your agent works?"},
    {"name": "Joey Pinhas", "company": "Datadog", "linkedin": None, "video": "How do you know your agent works?"},
    {"name": "Mustafa Ali", "company": "Method Financial", "linkedin": None, "video": "How we scaled 500m AI agents in production with 2 engineers"},
    {"name": "Nik Caryotakis", "company": "SuperDial", "linkedin": None, "video": "Voice AI: Your Bot Isn't Special"},
    {"name": "Rahul Sengottuvelu", "company": "Ramp", "linkedin": None, "video": "Scaffold Wisely"},
    {"name": "Dylan Babbs", "company": "Profound", "linkedin": None, "video": "The Agentic Future of Search"},
    {"name": "Colin Sidoti", "company": "Clerk", "linkedin": None, "video": "The Agentic Future of Search"},
    {"name": "Anirudh Kamath", "company": "Browserbase", "linkedin": None, "video": "The Agentic Future of Search"},
    {"name": "Gopal Raman", "company": "South Park Commons", "linkedin": None, "video": "The Agentic Future of Search"},
    {"name": "Karina Nguyen", "company": "OpenAI", "linkedin": None, "video": "Creating Agents That Co-Create"},
    {"name": "Maria de Lourdes Zollo", "company": "Bee.Computer", "linkedin": None, "video": "Building Perfect Memory"},
    {"name": "Ethan Sutin", "company": "Bee.Computer", "linkedin": None, "video": "Building Perfect Memory"},
    {"name": "Soumith Chintala", "company": "Meta PyTorch", "linkedin": None, "video": "What does it take to build a personal, local, private AI Agent"},
    {"name": "Chip Huyen", "company": "Independent", "linkedin": None, "video": "Challenges of Building Agents"},
    {"name": "Erik Bernhardsson", "company": "Modal Labs", "linkedin": None, "video": "The Ideal AI Engineering Platform"},
    {"name": "Ilan Bigio", "company": "OpenAI", "linkedin": None, "video": "Function calling is all you need"},
    {"name": "Mahesh Murag", "company": "Anthropic", "linkedin": None, "video": "Building (Agents) with Model Context Protocol"},
    {"name": "Noah Gundotra", "company": "Solana", "linkedin": None, "video": "Solana Lets Agents Create Wealth"},
    {"name": "Minki Jung", "company": "Independent", "linkedin": None, "video": "Flow Engineering 101"},
    {"name": "Omar Sanseviero", "company": "DeepMind", "linkedin": None, "video": "Open ML Universe: Models, Agents, and Beyond"},
    {"name": "Samuel Colvin", "company": "Pydantic Logfire", "linkedin": None, "video": "An Opinionated Blueprint for the Future of GenAI Applications"},
    {"name": "Deepam Mishra", "company": "AWS", "linkedin": None, "video": "Building Agentic Workflows with DeepSeek and Amazon Nova"},
    {"name": "Nick Huang", "company": "LangChain", "linkedin": None, "video": "How Clay Performs Agent Evaluation"},
    {"name": "Ratch Sujithan", "company": "Clay GTM", "linkedin": None, "video": "How Clay Performs Agent Evaluation"},
    {"name": "Mahmoud Abdelwahab", "company": "Neon", "linkedin": None, "video": "Build a personal AI email agent"},
    {"name": "Charles Packer", "company": "Letta", "linkedin": None, "video": "Agent Memory and the LLM OS"},
    {"name": "Suman Debnath", "company": "AWS", "linkedin": None, "video": "Agentic RAG with Vision Language Models"},
    {"name": "Nico Albanese", "company": "Vercel", "linkedin": None, "video": "Advanced AI Engineering with AI SDK"},
    {"name": "Dan Mason", "company": "Stride", "linkedin": None, "video": "Multi-Agent Workflows with MCP"},
    {"name": "Atin Sanyal", "company": "Galileo", "linkedin": None, "video": "Evaluate This! Mitigating Hallucinations in RAG & AI Agents"},
    {"name": "Erin Mikail", "company": "Galileo", "linkedin": None, "video": "Evaluate This! Mitigating Hallucinations in RAG & AI Agents"},
    {"name": "Praveen Durairaju", "company": "Hasura", "linkedin": None, "video": "Path towards 100% Accurate & Repeatable Data Agents"},
]

# Save to JSON
with open('ai_engineer_speakers.json', 'w') as f:
    json.dump(speakers_data, f, indent=2)

print(f"Total speakers identified: {len(speakers_data)}")
print("\nSpeakers saved to ai_engineer_speakers.json")

# Create a summary grouped by company
companies = {}
for speaker in speakers_data:
    company = speaker['company']
    if company not in companies:
        companies[company] = []
    companies[company].append(speaker['name'])

print(f"\nUnique companies: {len(companies)}")

