name: "🤖 Ask Claude"
description: "Ask Claude anything - emails, research, content, questions"
title: "@claude "
labels: ["claude"]
body:
  - type: markdown
    attributes:
      value: |
        **Just type your request after `@claude` in the title and submit!**
        
        ### Examples:
        
        | What you type | What happens |
        |---------------|--------------|
        | `@claude email ashvath@trynebula.ai` | Drafts personalized email |
        | `@claude research Anthropic` | Researches company as prospect |
        | `@claude linkedin 100M downloads milestone` | Drafts LinkedIn post |
        | `@claude competitor how to beat Pinecone` | Competitive analysis |
        | `@claude meeting summary from last week` | Summarizes recent meetings |
        | `@claude What are our Q1 priorities?` | Answers from GTM context |
