name: "🤖 Ask Claude"
description: "Ask Claude any GTM question"
title: "@claude "
labels: ["claude-question"]
body:
  - type: markdown
    attributes:
      value: |
        **Just type your question in the title after `@claude` and submit!**
        
        Examples:
        - `@claude What are our Q1 priorities?`
        - `@claude How should we position against Pinecone?`
        - `@claude Summarize recent meeting decisions`
