name: "⚔️ Competitor Intel"
description: "Get competitive intelligence"
title: "[Competitor] "
labels: ["competitor-intel"]
body:
  - type: markdown
    attributes:
      value: |
        **Just add your question to the title and submit!**
        
        Examples:
        - `[Competitor] How to position against Pinecone?`
        - `[Competitor] Weaviate's weaknesses`
        - `[Competitor] Compare pricing with TurboPuffer`
