name: "📧 Draft Email"
description: "Draft an outreach email"
title: "[Email] "
labels: ["draft-email"]
body:
  - type: markdown
    attributes:
      value: |
        **Just add company/contact info to the title and submit!**
        
        Examples:
        - `[Email] Notion - Ivan Zhao, CEO`
        - `[Email] Stripe - Patrick Collison`
        - `[Email] OpenAI - follow up after demo`
