name: "📧 Draft Email"
description: "Draft an outreach email"
title: "[Email] "
labels: ["draft-email"]
body:
  - type: markdown
    attributes:
      value: |
        **Just add the email address to the title and submit!**
        
        Examples:
        - `[Email] ashvath@trynebula.ai`
        - `[Email] ivan@notion.so`
        - `[Email] patrick@stripe.com`
        
        Claude will research the company and draft a personalized email.
