name: "📱 LinkedIn Post"
description: "Draft a LinkedIn post"
title: "[LinkedIn] "
labels: ["content", "linkedin"]
body:
  - type: markdown
    attributes:
      value: |
        **Just add the topic to the title and submit!**
        
        Examples:
        - `[LinkedIn] 100M downloads milestone`
        - `[LinkedIn] Why search accuracy matters for AI agents`
        - `[LinkedIn] Lessons from building context infrastructure`
