#!/usr/bin/env python3
"""
Draft Outreach Emails using Claude + GTM Context

Usage:
    python draft_outreach_email.py "Company Name" "Contact Name" "Their Role"
    python draft_outreach_email.py "Notion" "Ivan Zhao" "CEO"
    
Options:
    --send          Actually send via terminal email (requires mutt/msmtp setup)
    --template      Use a specific template (default: intro)
    --output        Save to specific file (default: drafts/YYYY-MM-DD_company.txt)
"""

import os
import sys
import json
import argparse
from datetime import datetime
from pathlib import Path

try:
    from anthropic import Anthropic
except ImportError:
    print("Please install anthropic: pip install anthropic")
    sys.exit(1)

# Get the project root
PROJECT_ROOT = Path(__file__).parent.parent

def load_gtm_context():
    """Load GTM context files for Claude."""
    context_parts = []
    
    files_to_load = [
        "CLAUDE.md",
        "context/GTM_CONTEXT.md",
        "LINKEDIN_OUTREACH_TEMPLATES.md",
    ]
    
    for file_path in files_to_load:
        full_path = PROJECT_ROOT / file_path
        if full_path.exists():
            content = full_path.read_text()
            context_parts.append(f"=== {file_path} ===\n{content}")
    
    return "\n\n".join(context_parts)

def get_email_templates():
    """Available email templates."""
    return {
        "intro": "Initial outreach introducing Chroma",
        "follow_up": "Follow-up after no response",
        "post_meeting": "Thank you after a meeting",
        "case_study": "Sharing relevant case study",
        "event": "Invitation to event or webinar",
    }

def draft_email(company: str, contact_name: str, role: str, template: str = "intro") -> dict:
    """Use Claude to draft an outreach email."""
    
    client = Anthropic()
    context = load_gtm_context()
    
    system_prompt = f"""You are an expert B2B sales copywriter for Chroma, the AI-native context layer.

CRITICAL RULES:
- NEVER say "vector database" - use "context layer" or "search infrastructure for AI"
- Be concise, professional, and value-focused
- No fluff or generic statements
- Reference specific pain points for their industry/role
- Include a clear, low-friction CTA

CHROMA POSITIONING:
- "Better search accuracy → lower token costs → better, faster, cheaper agents"
- 100M+ downloads, 25k+ GitHub stars
- Used by leading AI teams

GTM CONTEXT:
{context}

OUTPUT FORMAT:
Return a JSON object with:
{{
    "subject": "Email subject line",
    "body": "Full email body with proper formatting",
    "notes": "Internal notes about why this approach was chosen"
}}
"""

    templates_desc = get_email_templates()
    template_instruction = templates_desc.get(template, templates_desc["intro"])
    
    user_prompt = f"""Draft a {template} email for:

Company: {company}
Contact: {contact_name}
Role: {role}
Template Type: {template_instruction}

Research what {company} does and tailor the message to their specific needs.
Make it personal, not generic.
Keep it under 150 words for the body.
"""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}]
    )
    
    # Parse the response
    response_text = response.content[0].text
    
    # Try to extract JSON
    try:
        # Find JSON in response
        start = response_text.find('{')
        end = response_text.rfind('}') + 1
        if start != -1 and end > start:
            return json.loads(response_text[start:end])
    except json.JSONDecodeError:
        pass
    
    # Fallback: return as plain text
    return {
        "subject": f"Quick question for {contact_name}",
        "body": response_text,
        "notes": "Could not parse structured response"
    }

def save_draft(email_data: dict, company: str, output_path: str = None) -> str:
    """Save the draft email to a file."""
    
    # Create drafts directory
    drafts_dir = PROJECT_ROOT / "drafts"
    drafts_dir.mkdir(exist_ok=True)
    
    # Generate filename
    if output_path:
        file_path = Path(output_path)
    else:
        date_str = datetime.now().strftime("%Y-%m-%d")
        safe_company = company.lower().replace(" ", "_").replace("/", "_")
        file_path = drafts_dir / f"{date_str}_{safe_company}.txt"
    
    # Format the draft
    content = f"""TO: [Add recipient email]
SUBJECT: {email_data['subject']}
DATE: {datetime.now().strftime("%Y-%m-%d %H:%M")}
COMPANY: {company}

---

{email_data['body']}

---
INTERNAL NOTES:
{email_data.get('notes', 'N/A')}

---
Generated by Claude using Chroma GTM context
"""
    
    file_path.write_text(content)
    return str(file_path)

def send_with_mutt(email_data: dict, to_email: str):
    """Send email using mutt (requires mutt to be configured)."""
    import subprocess
    
    # Create temp file for body
    temp_file = "/tmp/email_body.txt"
    with open(temp_file, "w") as f:
        f.write(email_data['body'])
    
    # Mutt command
    cmd = [
        "mutt",
        "-s", email_data['subject'],
        to_email,
        "<", temp_file
    ]
    
    print(f"Would run: {' '.join(cmd)}")
    print("(Actual sending disabled for safety - edit script to enable)")
    
    # Uncomment to actually send:
    # subprocess.run(f'mutt -s "{email_data["subject"]}" {to_email} < {temp_file}', shell=True)

def main():
    parser = argparse.ArgumentParser(description="Draft outreach emails using Claude")
    parser.add_argument("company", help="Company name")
    parser.add_argument("contact", help="Contact name")
    parser.add_argument("role", help="Contact's role")
    parser.add_argument("--template", default="intro", choices=get_email_templates().keys(),
                        help="Email template type")
    parser.add_argument("--send", action="store_true", help="Send via mutt (requires setup)")
    parser.add_argument("--to", help="Recipient email (required with --send)")
    parser.add_argument("--output", help="Output file path")
    
    args = parser.parse_args()
    
    print(f"🤖 Drafting {args.template} email for {args.contact} at {args.company}...")
    
    # Draft the email
    email_data = draft_email(args.company, args.contact, args.role, args.template)
    
    print("\n" + "="*60)
    print(f"📧 SUBJECT: {email_data['subject']}")
    print("="*60)
    print(email_data['body'])
    print("="*60)
    
    # Save draft
    draft_path = save_draft(email_data, args.company, args.output)
    print(f"\n✅ Draft saved to: {draft_path}")
    
    # Optionally send
    if args.send:
        if not args.to:
            print("❌ Error: --to email required when using --send")
            sys.exit(1)
        send_with_mutt(email_data, args.to)
        print(f"📤 Email sent to {args.to}")
    else:
        print("\n💡 To send, use: --send --to recipient@email.com")
        print("   Or copy the draft and send manually")

if __name__ == "__main__":
    main()

